add napi file, modify makefile, for CreateKey.
intel/ehsm pull request #4
Opened 2021-11-25 11:48 UTC by Liang1XZhao

add napi file, implementation CreateKey function

2021-11-26 00:57 UTC, syan10 requested changes

2021-11-26 00:57 UTC, syan10 commented on core/Napi/ehsm_napi.cpp
> +extern "C" char* CreateKey_napi(int intMechanism, int intOrigin)
why the return code is "char *", is it must?

2021-11-26 00:57 UTC, syan10 commented on core/Napi/ehsm_napi.cpp
> +    rv = Initialize();
not call the finalize()?

2021-11-26 00:57 UTC, syan10 commented on core/App/ehsm_provider.cpp
> +    printf("==========CreateKey 1==========\n");
remove the unused logs

2021-11-26 00:57 UTC, syan10 commented on core/App/ehsm_provider.cpp
> +                printf("==========CreateKey 2.1==========\n");
same here

2021-11-26 00:57 UTC, syan10 commented on core/Napi/ehsm_napi.cpp.work
> +/*
this file for what?

2021-11-26 00:57 UTC, syan10 commented on core/Makefile
>  App_Name := ehsm-core
if you already split it to the libaray, please remove the original App target.

2021-11-26 00:59 UTC, syan10 requested changes
And, you should split this PR into serveral commits.

Only do one thing in one comimt.

2021-11-26 01:02 UTC, yang8621 commented on core/App/ehsm_provider.cpp
> +    /*status = enclave_la_create_session(enclaveHelpers.getSgxEnclaveId(), &ret_status);
keep these codes in the patch. It's for the local test only.

2021-11-26 01:38 UTC, yang8621 commented on core/Napi/ehsm_napi.cpp
> +    rest = (char *)malloc(128 * sizeof(uint8_t));
How to know 128 is big enough? 
Is it possible to use C++ STL and define the base64encoding as:
std::string EncodeBase64(const unsigned char* input_data, int input_num)?

2021-11-26 02:21 UTC, yang8621 commented on core/Napi/ehsm_napi.cpp
> +    rest = (char *)malloc(128 * sizeof(uint8_t));
FYI:
std::string base64_encoding(const unsigned char* input_data, int input_num) {
const char encode_table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
unsigned char batch_input[4] = { 0 };
std::string encode_str;
int length = 0;
for (int i = 0; i < (int)(input_num / 3); i++) {
batch_input[1] = *input_data++;
batch_input[2] = *input_data++;
batch_input[3] = *input_data++;
encode_str += encode_table[batch_input[1] >> 2];
encode_str += encode_table[((batch_input[1] << 4) | (batch_input[2] >> 4)) & 0x3F];
encode_str += encode_table[((batch_input[2] << 2) | (batch_input[3] >> 6)) & 0x3F];
encode_str += encode_table[batch_input[3] & 0x3F];



length +=4;
if (length == 76) {
encode_str += "\r\n";
length = 0;
}
}



int mod = input_num % 3;
if (mod == 2) {
batch_input[1] = *input_data++;
batch_input[2] = *input_data++;
encode_str += encode_table[(batch_input[1] & 0xFC) >> 2];
encode_str += encode_table[((batch_input[1] & 0x03) << 4) | ((batch_input[2] & 0xF0) >> 4)];
encode_str += encode_table[((batch_input[2] & 0x0F) << 2)];
encode_str += "=";
} else {
batch_input[1] = *input_data++;
encode_str += encode_table[(batch_input[1] & 0xFC) >> 2];
encode_str += encode_table[((batch_input[1] & 0x03) << 4)];
encode_str += "==";
}



return encode_str;
}

2021-11-30 01:11 UTC, syan10 commented on docker/Dockerfile
> +EXPOSE 3000
what's this for?

2021-11-30 01:12 UTC, syan10 commented on docker/Dockerfile
> +    && mv node-v16.13.0-linux-x64/ /usr/local/nodejs \
why not use apt-get install?  is it a prebuild nodejs?

2021-11-30 01:14 UTC, syan10 commented on ehsm-service/constans.js
> +const pramas = {
change the filename "constans.js" to make more meaningful

2021-11-30 01:15 UTC, syan10 commented on ehsm-service/index.js
> +const express = require('express')
same to this file name..

2021-11-30 01:17 UTC, syan10 commented on ehsm-service/index.js
> +      const CreateKey_r = CreateKey_napi.CreateKey_napi(intMechanism, intOrigin);
so is it must to return a string for the function 'CreateKey_napi", can we put the result_string as a output parameter?

2021-12-01 01:59 UTC, syan10 commented
please create a new PR for the change, and i will abandon it now

2021-12-01 01:59 UTC, closed without merging